
from kagan.database.models import TicketPriority, TicketStatus

DEFAULT_DB_PATH = ".kagan/state.db"
DEFAULT_CONFIG_PATH = ".kagan/config.toml"
DEFAULT_LOCK_PATH = ".kagan/kagan.lock"

COLUMN_ORDER = [
    TicketStatus.BACKLOG,
    TicketStatus.IN_PROGRESS,
    TicketStatus.REVIEW,
    TicketStatus.DONE,
]

STATUS_LABELS = {
    TicketStatus.BACKLOG: "BACKLOG",
    TicketStatus.IN_PROGRESS: "IN PROGRESS",
    TicketStatus.REVIEW: "REVIEW",
    TicketStatus.DONE: "DONE",
}

PRIORITY_LABELS = {
    TicketPriority.LOW: "Low",
    TicketPriority.MEDIUM: "Medium",
    TicketPriority.HIGH: "High",
}

# Timeouts (seconds)
AGENT_WAIT_TIMEOUT = 30.0
REVIEW_AGENT_WAIT_TIMEOUT = 60.0
PROCESS_STOP_TIMEOUT = 5.0
HELP_NOTIFICATION_TIMEOUT = 5

# Intervals (seconds)
SCHEDULER_TICK_INTERVAL = 2.0
ACTIVE_CARDS_UPDATE_INTERVAL = 1.0
CARD_PULSE_INTERVAL = 0.6
TERMINAL_POLL_INTERVAL = 0.1

# Buffer sizes
MESSAGE_BUFFER_LIMIT = 500
SUBPROCESS_BUFFER_SIZE = 10 * 1024 * 1024  # 10MB
TERMINAL_READ_CHUNK_SIZE = 8192
SCRATCHPAD_MAX_SIZE = 50000
OUTPUT_TRUNCATE_LIMIT = 5000

# UI constraints
TERMINAL_MIN_WIDTH = 80
TERMINAL_MIN_HEIGHT = 20
DRAG_THRESHOLD_PIXELS = 5
TITLE_MAX_LENGTH = 18
DESCRIPTION_MAX_LENGTH = 15

# Display limits
KNOWLEDGE_SEARCH_DEFAULT_LIMIT = 5
SHORT_ID_LENGTH = 4
HAT_DISPLAY_LENGTH = 8
