export const BOARD_BINDINGS = [
  { key: "j,down", cmd: "kagan.down", desc: "Next row (card or subtask)", short: "down" },
  { key: "k,up", cmd: "kagan.up", desc: "Previous row (card or subtask)", short: "up" },
  { key: "shift+j", cmd: "kagan.reorder_down", desc: "Move card down in column", short: "reorder down" },
  { key: "shift+k", cmd: "kagan.reorder_up", desc: "Move card up in column", short: "reorder up" },
  { key: "g", cmd: "kagan.first", desc: "Select first row in column", short: "first" },
  { key: "shift+g", cmd: "kagan.last", desc: "Select last row in column", short: "last" },
  { key: "l,right", cmd: "kagan.next_column", desc: "Next column", short: "next col" },
  { key: "h,left", cmd: "kagan.prev_column", desc: "Previous column", short: "prev col" },
  { key: "m", cmd: "kagan.move_next", desc: "Move to next column", short: "move >" },
  { key: "b", cmd: "kagan.move_prev", desc: "Move to previous column", short: "move <" },
  { key: "n", cmd: "kagan.new", desc: "New task", short: "new" },
  { key: "o", cmd: "kagan.open_session", desc: "Open selected session", short: "open" },
  { key: "return", cmd: "kagan.menu", desc: "Open the card action menu", short: "menu" },
  { key: "d", cmd: "kagan.delete", desc: "Delete selected session", short: "delete" },
  { key: "a", cmd: "kagan.approve", desc: "Approve task", short: "approve" },
  { key: "s", cmd: "kagan.send_back", desc: "Send back for another iteration", short: "send back" },
  { key: "r", cmd: "kagan.retry", desc: "Restart intake or review", short: "restart" },
  { key: "p", cmd: "kagan.permissions", desc: "Review waiting permission requests", short: "permissions" },
  { key: "/", cmd: "kagan.filter", desc: "Filter cards", short: "filter" },
  { key: "?", cmd: "kagan.help", desc: "Show help", short: "help" },
  { key: ",", cmd: "kagan.settings", desc: "Open settings", short: "settings" },
  { key: "q", cmd: "kagan.close", desc: "Close Kagan", short: "quit" },
  { key: "escape", cmd: "kagan.dismiss", desc: "Dismiss help or clear filter", short: "dismiss" },
] as const
